 format = """\
$directory\
$git_branch\
$git_status\
$username\
$hostname\
$cmd_duration\
$line_break\
$conda\
$character\
"""

[directory]
truncation_length = 10
truncate_to_repo = false
format = "[$path](purple)[$read_only](purple) "

[git_branch]
format = "[$branch](fg:245)"
always_show_remote = true

[git_status]
format = "[$all_status](red)"

[username]
format = " [$user@](fg:245)"

[hostname]
format = "[$hostname](fg:245)"

[cmd_duration]
format = " [$duration](bold yellow)"

[conda]
format = "[$environment](fg:245) "

[character]
success_symbol = "[❯](bold fg:147)"
error_symbol = "[❯](bold red)"